### ISSUE TITLE
更新后真寻启动报错

### ISSUE THREAD

**Issue by INSide-734** [RShock/ikun_evolution#6]
`03-04 19:39:01 [ERROR] nonebot | Failed to import "ikun_evolution"
Traceback (most recent call last):
  File "/root/zhenxun_bot/bot.py", line 17, in <module>
    nonebot.load_plugins("extensive_plugin")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/zhenxun_bot/extensive_plugin/ikun_evolution/__init__.py", line 16, in <module>
    from .service import game_handler, player_handler, skill_handler, battle_handler, adv_handler
  File "/root/zhenxun_bot/extensive_plugin/ikun_evolution/service/player_handler.py", line 6, in <module>
    from services import db
ImportError: cannot import name 'db' from 'services' (/root/zhenxun_bot/services/__init__.py)`

**Comment by RShock** [comment]
我曾私下给zhenxun提出意见：Gino这个库已经过时了，他依赖于sqlalchemy1.3版本且无人维护，在主流库是sqlalchemy1.4的当下会产生越来越多的问题
zhenxun_bot在最近的大更新中移除了Gino换成了tortoise[更新记录](https://github.com/HibiKier/zhenxun_bot/commit/7685b95031e27dab947a2bf08b37a47958682402#diff-35a01a15ce54da1b505177f70b27959a7b4ee9ec129a04d73c6b89a33923db71)
因此，我的炒股和只因插件报废，这是计划内的更换成本。
因为持久层代码被修改，本问题需要等我大更代码之后才能解决，对我来说，tortoise也是一个全新的概念，所以需要时间。如果你有一些编程能力的话，可以尝试自己准备一个Gino塞进去应急（我移植到nb那边的插件就是这样做的），或者等待我的修复。
